# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49daa5bedbd0f17da9d1bfc5a1e43952bf13ee72f9906a5a8432da2de5dcb4cdcf80c27e0e465cda255cd46cb7f0a6c5290d5b516029255dff2bcac9b6fbac4a

test:
  secret_key_base: aac69495b7433e377c8bf1ff75946d4e7372cc2568fe480c58cfccbab5366909d9548b4b62181466c3ba93a500910792f7e7f0e481ee9e95049c71476d09cb86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
